-intstyle "ise" -incremental -lib "secureip" -o "E:/Universidad/Telematica/4o/SOCS-FPGAS/lab1/lab1etb_isim_beh.exe" -prj "E:/Universidad/Telematica/4o/SOCS-FPGAS/lab1/lab1etb_beh.prj" "work.lab1etb" 
