-intstyle "ise" -incremental -lib "secureip" -o "E:/Universidad/Telematica/4o/SOCS-FPGAS/lab2/lab2_tb_isim_beh.exe" -prj "E:/Universidad/Telematica/4o/SOCS-FPGAS/lab2/lab2_tb_beh.prj" "work.lab2_tb" 
