-intstyle "ise" -incremental -lib "secureip" -o "E:/Universidad/Telematica/4o/SOCS-FPGAS/lab3/lab3atb_isim_beh.exe" -prj "E:/Universidad/Telematica/4o/SOCS-FPGAS/lab3/lab3atb_beh.prj" "work.lab3atb" 
